### ISSUE TITLE
copying content of one folder to another folder

### ISSUE THREAD

**Issue by jaroslaw-weber** [webdesus/fs_extra#11]
hey. I want to copy all files and folders from "a" folder to "b" folder. I tried to use `dir::get_dir_content` and iterate with `::copy_item`, but I couldn't came up with a simple solution. I was able to copy "a" folder inside the "b" folder, but this is not what I want to do.

Is there a simple solution to this problem? If yes, I would love to see it in examples. If no, an additional function would be great.

**Comment by webdesus** [comment]
If folder "b" doesn't have exist then you can use `copy_inside` option(#5 )

I think it's interesting function for realise. But now I do not have time, and i don't know when i can make it this function(maybe in 2-3 weeks I can).

**Comment by jaroslaw-weber** [comment]
folder "b" exists actually and has files in it already :)
it's not a big issue ( but it would be nice to have some kind of option to do it.

**Comment by matklad** [comment]
I think one way to achieve that would be adding 

```
/// The name of the resulting dir, defaults to the name of the source dir. 
dir_name: Option<OsString>,
```

and changing

```
        if let Some(dir_name) = from.components().last() {
            to.push(dir_name.as_os_str());
```

to something like

```
dir_name = options.dir_name.or_else(|| from.components().last())
```

**Comment by matklad** [comment]
Hm, I feel there’s some misunderstanding here? Let me restate the facts I believe are true.

Currently, when I copy path/A to path/B, I get path/B/A, because the last component of the source path is unconditionally appended to the test inaction path. There’s no API which allows me to get path/B/C, where the “contents” of path/A and path/B/C is the same.

My proposal for dir name was exactly about allowing users to change path/B/A to path/B/C.

**Comment by webdesus** [comment]
In this issue discuss another problem. When a user wants copy recursive all content from folder A to B without creating dir A name inside B or name different. 

But you talking about change destination folder name. I think if this issue was being closed, your problem automatical will be fixed. You will write from `path/A` to `path/B/C` using a new flag which will be copied inside all content.

**Comment by webdesus** [comment]
I'm committed new feature(new flag content_only). But new version(1.2) planned to publish on this week. I planed add one more feature.

While you can use git path to master branch in your cargo.toml file :smiley:  

@matklad it's enough for your tasks?))) Or you have another case?

**Comment by awakecoding** [comment]
+1 I just started using fs_extra today, and I needed exactly this feature. I have pointed my cargo.toml to the git repository for now.

**Comment by webdesus** [comment]
Wow ... I didn't think so popular case. Next time I will publish new features faster, promise :wink:
